INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'online_shop_menu', 'مشاهده منو فروشگاه آنلاین', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'order_view', 'مشاهده لیست سفارشات آنلاین', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'order_details_view', 'مشاهده جزئیات سفارش آنلاین', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'change_order_status', 'تغییر وضعیت سفارش', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'change_order_payment_status', 'تغییر وضعیت پرداخت سفارش', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'insert_order_tracking_number', 'درج کدرهگیری مرسوله', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'view_transaction', 'مشاهده تراکنش‌های آنلاین', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'view_merchants', 'مشاهده تسویه حساب', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'view_front_menu', 'مشاهده چیدمان منو', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'update_front_menu', 'بروزرسانی چیدمان منو', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'page_builder', 'صفحه‌ساز فروشگاه', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'order_histories', 'مشاهده تاریخچه سفارش', '2022-12-22 06:54:41', '2022-12-22 06:54:41');
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'order_cost', 'مشاهده هزینه‌های سفارش', '2022-12-22 06:54:41', '2022-12-22 06:54:41');

INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'general_setting_view', 'مشاهده تنظیمات عمومی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'general_setting_update', 'بروزرسانی تنظیمات عمومی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'shipping_setting_view', 'مشاهده تنظیمات حمل‌ونقل', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'shipping_setting_update', 'بروزرسانی تنظیمات حمل‌ونقل', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_setting_view', 'مشاهده تنظیمات سرویس افزودنی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_enamad_setting_update', 'بروزرسانی تنظیمات نماد اعتماد', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_samandehi_setting_update', 'بروزرسانی تنظیمات ساماندهی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_mediaad_setting_update', 'بروزرسانی تنظیمات مدیااد', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_goftino_setting_update', 'بروزرسانی تنظیمات گفتینو', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_gtag_setting_update', 'بروزرسانی تنظیمات گوگل آنالیتیکس', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_ippanel_setting_update', 'بروزرسانی تنظیمات ippanel', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_zibal_setting_update', 'بروزرسانی تنظیمات زیبال', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'third_party_telegram_setting_update', 'بروزرسانی تنظیمات تلگرام', NULL, NULL);

INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'sliders_view', 'مشاهده اسلایدر‌ها', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'sliders_create', 'ایجاد اسلایدر', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'sliders_edit', 'ویرایش اسلایدر', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'sliders_delete', 'حذف اسلایدر', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'slider_item_create', 'ایجاد تصاویر اسلایدر', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'slider_item_delete', 'حذف تصاویر اسلایدر', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'banners_view', 'مشاهده بنر‌ها', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'banners_create', 'ایجاد بنر', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'banners_edit', 'ویرایش بنر', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'banners_delete', 'حذف بنر', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'homes_view', 'مشاهده چیدمان‌ها', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'homes_create', 'ایجاد چیدمان', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'homes_edit', 'ویرایش چیدمان', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'homes_delete', 'حذف چیدمان', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'home_item_create', 'ایجاد آیتم چیدمان', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'home_item_delete', 'حذف آیتم چیدمان', NULL, NULL);

INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'attribute_group_view', 'مشاهده گروه‌ویژگی‌ها', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'attribute_group_create', 'ایجاد گروه‌ویژگی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'attribute_group_edit', 'ویرایش گروه‌ویژگی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'attribute_group_delete', 'حذف گروه‌ویژگی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'size_guide_view', 'مشاهده گروه‌ویژگی‌ها', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'size_guide_create', 'ایجاد گروه‌ویژگی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'size_guide_edit', 'ویرایش گروه‌ویژگی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'size_guide_delete', 'حذف گروه‌ویژگی', NULL, NULL);
INSERT INTO `permissions` (`id`, `name`, `display_name`, `created_at`, `updated_at`) VALUES (NULL, 'show_reports_profit_loss', 'مشاهده گزارش سود و زیان', NULL, NULL);
